CREATE TABLE Account(
	id INT PRIMARY KEY,
    name VARCHAR(20) UNIQUE,
    balance INT NOT NULL DEFAULT 0
);

-- ADD NEW COLUMN
ALTER TABLE Account ADD Interest FLOAT NOT NULL DEFAULT 0;

-- MODIFY DATA TYPE OF EXISTING COLUMNS
ALTER TABLE Account MODIFY Interest DOUBLE NOT NULL DEFAULT 0;

-- RENAME COLUMN
ALTER TABLE Account CHANGE COLUMN Interest Saving_interest FLOAT NOT NULL DEFAULT 0;

-- DROP COLUMN
ALTER TABLE Account DROP COLUMN SAVING_INTEREST;

-- CHANGE TABLE NAME
ALTER TABLE Account RENAME TO Account_details;

DESC Account_details;