CREATE TABLE Worker(
	WORKER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME CHAR(25),
    LAST_NAME CHAR(25),
    SALARY INT(15),
    JOINING_DATE DATE,
    DEPT CHAR(25)
);

INSERT INTO Worker
			(WORKER_ID , FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPT) VALUES
            (001, 'Vaibhav', 'Nath', 100000, '16-02-17', 'HR'), 
            (002, 'Virat', 'Nath', 200000, '03-02-20', 'IT');
            
INSERT INTO Worker VALUES (003,'Prithvi','Nath', 150000, '15-08-21', 'ADMIN');

INSERT INTO Worker
			(WORKER_ID , FIRST_NAME, LAST_NAME) VALUES
            (004, 'Sam','Karan');
            
SELECT * FROM Worker;

-- UPDATE COMMAND
UPDATE Worker SET SALARY=120000, DEPT='HR' WHERE WORKER_ID = 004;

-- UPDATE MULTIPLE ROWS
SET SQL_SAFE_UPDATES = 0;
UPDATE Worker SET DEPT = 'ACCOUNT';
UPDATE Worker SET SALARY = SALARY +10000;

-- DELETE COMMAND
DELETE FROM Worker WHERE WORKER_ID = 004;

-- DELETE ENTIRE TABLE
DELETE FROM Worker;