USE University;
-- WHERE CLAUSE
-- EMP WITH AGE > 29
SELECT * FROM emp WHERE Age > 29;
SELECT * FROM emp WHERE Age IN (SELECT Age FROM emp WHERE Age > 29);

-- EMP DETAILS WOKRING IN MORE THAN 1 PROJECTS
SELECT * FROM emp WHERE id IN (SELECT empID FROM Project GROUP BY empID HAVING COUNT(empID)>1);


-- SINGLE VALUE SUBQUERY
-- DETILA OF EMP HAVING AGE GRETAER THAN AVG AGE
SELECT * FROM emp WHERE Age > (SELECT AVG(Age) FROM emp);


-- FROM CLAUSE (uses derived table)
-- SELECT MAX AGE PERSON WHOSE NAME contains'A'
SELECT MAX(Age) FROM (SELECT * FROM emp WHERE fname LIKE '%a%')AS temp;


-- CORELATED SUBQUERY
-- FIND THIRD OLDEST EMPLOYEE
SELECT * FROM Emp e1 WHERE 3 = (SELECT COUNT(e2.AGE) FROM Emp e2 WHERE e2.Age >= e1.Age);
